### ISSUE TITLE
RG2 rviz moveit

### ISSUE THREAD

**Issue by masterdeki** [Osaka-University-Harada-Laboratory/onrobot#16]
Is it possible to control RG2 gripper from rviz and moveit?

**Comment by takuya-ki** [comment]
No, at the moment. If you create it, please tell me and contribute to updating this repository.
However, I could not understand why you need moveit since the hands have only one degree of freedom.

**Comment by masterdeki** [comment]
moveit is not necessary, but rviz is. I'm trying to make real ur5e and rg2 both work from rviz but there is some errors with controllers for gripper I cant fix.
