### ISSUE TITLE
Can this feature pack be used on UR5?

### ISSUE THREAD

**Issue by sunnymints** [Osaka-University-Harada-Laboratory/onrobot#2]
My RG2 is mounted on UR5, can this package operate the jaws directly through the UR5 communication?

**Comment by alexandrosnic** [comment]
Hey @sunnymints, did you find a solution for how to control the tool that is connected to the end-effector of the UR5?

**Comment by takuya-ki** [comment]
It seems to me that this issue is not related to this repository so I close this.
