### ISSUE TITLE
Installation warn

### ISSUE THREAD

**Issue by sunnymints** [Osaka-University-Harada-Laboratory/onrobot#3]
`catkin_make` ok
`sudo rosdep install --from-paths ./src --ignore-packages-from-source --rosdistro noetic -y --os=ubuntu:focal -y`---->`ERROR: your rosdep installation has not been initialized yet.  Please run:

    rosdep update
`but we have initialized the ros!
`catkin build -DPYTHON_EXECUTABLE=/usr/bin/python3
`-----> `NO find this command`

**Comment by takuya-ki** [comment]
@sunnymints 
I am not sure what your questions are from the above comments but if you could not use catkin build please try below.
`apt install python3-catkin-tools`
Also, please reply to my answer to [another issue](https://github.com/Osaka-University-Harada-Laboratory/onrobot/issues/2) when you have time.
